library(here)
source(here("pipeline/obesity_trend.R"))
source(here("pipeline/equating.R"))
source(here("pipeline/run_hall.R"))
source(here("pipeline/extrapolate.R"))
source(here("pipeline/main_charts.R"))
source(here("pipeline/edi_charts.R"))
